### ISSUE TITLE
Not emulator - bin vs build

### ISSUE THREAD

**Issue by MichalSkoula** [MichalSkoula/arco-1500#16]

**Comment by ddonatek** [comment]
**bin** - directory with all game binaries
when game is built (in **build**), its binary is moved to **bin**

**build** - directory where games are built, currently shared by all games
in the future, every game will have its own directory inside the **build** dir
(so for example when you build_all.sh it will only rebuild games that had changed)

also, in the future, cmake will probably be used instead of shell script

close plz

**Comment by MichalSkoula** [comment]
ok, i hope it is ok 🙏
